### ISSUE TITLE
repo sync issues

### ISSUE THREAD

**Issue by ghost** [DroidX-UI/manifest#13]
manifests:
fatal: couldn't find remote ref refs/heads/14_r29
manifests: sleeping 4.0 seconds before retrying
fatal: cannot obtain manifest https://github.com/DroidX-UI/manifest.git
================================================================================
Repo command failed: UpdateManifestError
        Unable to sync manifest default.xml

R31
fatal: manifest 'default.xml' not available
fatal: remove-project element specifies non-existent project: <remove-project name="device/generic/qemu"/>
================================================================================
Repo command failed: UpdateManifestError
        Unable to sync manifest default.xml

**Comment by MODEDGES24** [comment]
Hello source is wip right now thanks
