### ISSUE TITLE
Track taro hals 

### ISSUE THREAD

**Issue by SharmagRit** [DroidX-UI/manifest#6]
pls track taro hals and opensource from los.
https://github.com/RisingTechOSS/android/commit/68c8a35bb3eece38e5145c373707f91ff28ec092

https://github.com/LineageOS/android_vendor_qcom_opensource_display-commonsys-intf.git

https://github.com/LineageOS/android_vendor_qcom_opensource_interfaces.git

**Comment by ashwani212** [comment]
@SharmagRit @Haidar1417 @HyperPower17

**Comment by NRanjan-17** [comment]
Ok

**Comment by NRanjan-17** [comment]
https://github.com/DroidX-UI/manifest/commit/5446e3c663b455c49ec1040564562fc7d4ef2108

https://github.com/DroidX-UI/manifest/commit/381810b7925a31dde558d71475c8e2ea09d65be0

**Comment by SharmagRit** [comment]
Shukriya ❤️

**Comment by SuperiorPsycho** [comment]
@NRanjan-17 😲😲😲😲😲😲😲😲😲😲😲😲😲😲😲😲😲😲😲😲😲😲

**Comment by SuperiorPsycho** [comment]
@SuperiorPsycho Ok I won't reply I promise
